### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by esauri** [TeamVenu/venu#66]
Create a heatmap outside of venu. Location coordinates must be accessed from the firebase database.

Please follow the style of the current map. 
* Data is in ```fixtures/map-styles.json```
* As for the color of the gradients you will find green, red, yellow etc. under ```app/global-styles.js```

Guide:
* https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap
* https://console.firebase.google.com/project/venu-754b2/overview
* https://firebase.google.com/docs/database/web/read-and-write

**Comment by esauri** [comment]
locations are stored in an array called locations in the database

**Comment by iselleck** [comment]
Link: https://heatmaptest-d80f8.firebaseapp.com/

**Comment by esauri** [comment]
Looks good make sure to update the map styles to the current one so we can see the buildings.

**Comment by iselleck** [comment]
Updated style of gradient and map
